packages: []

catalogs:
  build:
    '@unocss/eslint-config': ^66.3.2
    beasties: ^0.3.4
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.44.1
    unocss: ^66.3.2
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.0
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.0
    vite-plugin-pwa: ^1.0.1
    vite-plugin-vue-devtools: ^7.7.7
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.0.0
    vite-ssg-sitemap: ^0.9.0

  dev:
    '@antfu/eslint-config': ^4.16.2
    '@iconify-json/carbon': ^1.2.10
    eslint: ^9.30.1
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    taze: ^19.1.0
    typescript: ^5.8.3

  frontend:
    '@unhead/vue': ^2.0.11
    '@unocss/reset': ^66.3.2
    '@vueuse/core': ^13.4.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.17
    vue-i18n: ^11.1.7
    vue-router: ^4.5.1

  types:
    '@types/node': ^24.0.10
    '@types/nprogress': ^0.2.3

  vine:
    '@vue-vine/eslint-config': ^1.1.4
    vue-vine: ^1.5.5
    vue-vine-tsc: ^1.5.5

onlyBuiltDependencies:
  - esbuild
