packages: []

catalogs:
  build:
    '@unocss/eslint-config': ^66.2.3
    beasties: ^0.3.4
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.44.0
    unocss: ^66.2.3
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.2.0
    vite-plugin-pwa: ^1.0.0
    vite-plugin-vue-devtools: ^7.7.7
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^27.0.1
    vite-ssg-sitemap: ^0.9.0

  dev:
    '@antfu/eslint-config': ^4.15.0
    '@iconify-json/carbon': ^1.2.9
    cypress: ^14.5.0
    cypress-vite: ^1.6.0
    eslint: ^9.29.0
    eslint-plugin-cypress: ^5.1.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    taze: ^19.1.0
    typescript: ^5.8.3
    vue-tsc: ^2.2.10

  frontend:
    '@unhead/vue': ^2.0.10
    '@unocss/reset': ^66.2.3
    '@vueuse/core': ^13.4.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.17
    vue-i18n: ^11.1.6
    vue-router: ^4.5.1

  types:
    '@types/nprogress': ^0.2.3

  vine:
    '@vue-vine/eslint-config': ^1.1.3
    vue-vine: ^1.5.1

onlyBuiltDependencies:
  - cypress
  - esbuild
